version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s %(levelname)s [%(name)s] %(message)s'
  response:
    format: '%(asctime)s ID:%(id)d [%(server)s] [%(tag)s] [%(peer)s] %(proto)s %(code)s %(rtime).6f %(q)s %(rrjson)s %(arjson)s %(aujson)s'
  clientresponse:
    format: '%(asctime)s ID:%(id)d [%(server)s] [%(tag)s] %(code)s %(rtime).6f %(q)s %(rrjson)s %(arjson)s %(aujson)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  response:
    formatter: response
    class: logging.NullHandler
    level: ERROR
  clientresponse:
    formatter: clientresponse
    class: logging.NullHandler
    level: ERROR
loggers:
  dnsss:
    level: INFO
    handlers: [default]
    propagate: no
  dnsss.server.response:
    level: INFO
    handlers: [response]
    propagate: no
  dnsss.client.response:
    level: INFO
    handlers: [clientresponse]
    propagate: no
root:
  level: INFO
  handlers: [default]
  propagate: no