from __future__ import annotations

DEFAULT_ALG = 'bind'
DEFAULT_FORMAT = 'table'
DEFAULT_QNAME = 'google.com'
DEFAULT_TABLEFMT = 'simple'
INTERVAL_MAX = 300.0
INTERVAL_MIN = 0.001
INTERVAL_STEP = 1.5
INTERVAL_START = 1.0
SELECT_TIMEOUT = 0.01
SERVER_SLEEP_DELAY = 0.1
TCP_BUF_SIZE = 8192
YAML_FLOAT_PRECISION = 6
YAML_FLOAT_FMT = f'.{YAML_FLOAT_PRECISION}f'